from pathlib import Path
import sys

import numpy as np
import pandas as pd
import streamlit as st


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

SRC_DIR = PROJECT_ROOT / "src"
DATA_DIR = PROJECT_ROOT / "data" / "raw" / "visuelle2"
RESULTS_DIR = PROJECT_ROOT / "results"

sys.path.insert(0, str(SRC_DIR))


# ============================================================
# PROJECT IMPORTS
# ============================================================

from normalization import inverse_transform
from inventory import (
    calculate_safety_stock,
    calculate_reorder_point,
)


# ============================================================
# STREAMLIT CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Fashion Demand & Inventory Optimization",
    page_icon="👕",
    layout="wide",
)


# ============================================================
# CONSTANTS
# ============================================================

HISTORY_COLUMNS = [
    str(i)
    for i in range(11)
]

METADATA_COLUMNS = [
    "external_code",
    "retail",
    "season",
    "category",
]

MODEL_DISPLAY_NAMES = {
    "xgboost": "XGBoost",
    "lstm": "LSTM",
    "naive": "Naive",
    "ses": "SES",
    "sarima": "SARIMA",
}


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        margin-bottom: 0.2rem;
    }

    .subtitle {
        font-size: 1rem;
        color: #777;
        margin-bottom: 1.5rem;
    }

    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# DATA LOADING
# ============================================================

@st.cache_data
def load_test_data():
    """
    Load the Visuelle 2.0 normalized test dataset.
    """

    path = DATA_DIR / "stfore_test.csv"

    if not path.exists():
        raise FileNotFoundError(
            f"Test dataset not found:\n{path}"
        )

    df = pd.read_csv(path)

    if "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])

    return df


@st.cache_data
def load_restocks():
    """
    Load historical restock events.

    IMPORTANT:
    qty in restocks.csv is already expressed in actual units.
    It must NOT be multiplied by 53.
    """

    path = DATA_DIR / "restocks.csv"

    if not path.exists():
        raise FileNotFoundError(
            f"Restock dataset not found:\n{path}"
        )

    return pd.read_csv(path)


@st.cache_data
def load_predictions(model_name):
    """
    Load predictions generated by the selected model.
    """

    path = (
        RESULTS_DIR
        / f"{model_name}_predictions.csv"
    )

    if not path.exists():
        return None

    return pd.read_csv(path)


@st.cache_data
def load_model_comparison():
    """
    Load final five-model comparison results.
    """

    path = (
        RESULTS_DIR
        / "model_comparison.csv"
    )

    if not path.exists():
        return None

    return pd.read_csv(path)


# ============================================================
# INVENTORY HELPERS
# ============================================================

def calculate_remaining_stock(
    normalized_restock,
    normalized_history
):
    """
    Estimate remaining available stock.

    Visuelle 2.0 forecasting values are normalized.

    Normalization scalar = 53

    Actual units = normalized value * 53

    Historical legitimate sales are deducted from
    the normalized restock allocation.
    """

    try:
        normalized_restock = float(
            normalized_restock
        )

    except (TypeError, ValueError):
        return 0.0

    if not np.isfinite(
        normalized_restock
    ):
        return 0.0

    normalized_restock = max(
        normalized_restock,
        0.0
    )

    normalized_history = np.asarray(
        normalized_history,
        dtype=float
    )

    normalized_history = np.nan_to_num(
        normalized_history,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    )

    normalized_history = np.maximum(
        normalized_history,
        0.0
    )

    cumulative_sales = 0.0

    for sales in normalized_history:

        sales = float(sales)

        if (
            cumulative_sales + sales
            <= normalized_restock
        ):

            cumulative_sales += sales

        else:

            remaining = max(
                normalized_restock
                - cumulative_sales,
                0.0
            )

            cumulative_sales += remaining

            break

    remaining_normalized = max(
        normalized_restock
        - cumulative_sales,
        0.0
    )

    remaining_units = float(
        inverse_transform(
            remaining_normalized
        )
    )

    return max(
        remaining_units,
        0.0
    )


# ============================================================
# HISTORICAL RESTOCK SUMMARY
# ============================================================

def build_restock_summary(restocks):
    """
    Build historical restock statistics.

    IMPORTANT:
    restocks.csv -> qty is already actual units.

    DO NOT multiply qty by 53.
    """

    summary = (
        restocks
        .groupby(
            [
                "external_code",
                "retail",
            ],
            as_index=False,
        )
        .agg(
            total_restock_units=(
                "qty",
                "sum",
            ),
            restock_events=(
                "qty",
                "count",
            ),
            average_restock_units=(
                "qty",
                "mean",
            ),
        )
    )

    return summary


# ============================================================
# PRODUCT RESTOCK HISTORY
# ============================================================

def get_product_restock_history(
    restocks,
    external_code,
    retail,
):
    """
    Return historical restock events for a
    product-store combination.
    """

    result = restocks[
        (
            restocks["external_code"]
            == external_code
        )
        &
        (
            restocks["retail"]
            == retail
        )
    ].copy()

    if result.empty:
        return result

    result["restock_units"] = (
        pd.to_numeric(
            result["qty"],
            errors="coerce",
        )
        .fillna(0.0)
    )

    return result.sort_values(
        [
            "year",
            "week",
        ],
        ascending=False,
    )


# ============================================================
# PAGE HEADER
# ============================================================

st.markdown(
    '<div class="main-title">'
    '👕 AI-Driven Fashion Demand Forecasting'
    '</div>',
    unsafe_allow_html=True,
)

st.markdown(
    '<div class="subtitle">'
    'Demand forecasting and inventory optimization '
    'for digital fashion supply chains'
    '</div>',
    unsafe_allow_html=True,
)


# ============================================================
# LOAD DATA
# ============================================================

try:

    test_df = load_test_data()
    restocks_df = load_restocks()

except Exception as error:

    st.error(
        f"Unable to load dataset:\n{error}"
    )

    st.stop()


# ============================================================
# VALIDATE REQUIRED TEST DATA COLUMNS
# ============================================================

required_test_columns = (
    METADATA_COLUMNS
    + ["restock"]
    + HISTORY_COLUMNS
    + ["11"]
)

missing_test_columns = [
    column
    for column in required_test_columns
    if column not in test_df.columns
]

if missing_test_columns:

    st.error(
        "The test dataset is missing required columns:"
    )

    st.write(
        missing_test_columns
    )

    st.stop()


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header(
    "Dashboard Controls"
)


# ============================================================
# DETECT AVAILABLE MODELS
# ============================================================

available_models = []

for model_name in [
    "xgboost",
    "lstm",
    "naive",
    "ses",
    "sarima",
]:

    prediction_path = (
        RESULTS_DIR
        / f"{model_name}_predictions.csv"
    )

    if prediction_path.exists():

        available_models.append(
            model_name
        )


if not available_models:

    st.error(
        "No model prediction files were found."
    )

    st.info(
        "Run the forecasting models first."
    )

    st.stop()


# ============================================================
# MODEL SELECTOR
# ============================================================

model_choice = st.sidebar.selectbox(
    "Forecasting Model",
    available_models,
    format_func=lambda x:
        MODEL_DISPLAY_NAMES.get(
            x,
            x,
        ),
)


# ============================================================
# LEAD TIME
# ============================================================

lead_time = st.sidebar.number_input(
    "Lead Time (periods)",
    min_value=1,
    max_value=12,
    value=1,
    step=1,
)


# ============================================================
# SERVICE LEVEL
# ============================================================

service_level = st.sidebar.selectbox(
    "Service Level",
    [
        0.90,
        0.95,
        0.975,
        0.99,
    ],
    index=1,
    format_func=lambda x:
        f"{x * 100:.1f}%",
)


# ============================================================
# LOAD MODEL PREDICTIONS
# ============================================================

prediction_df = load_predictions(
    model_choice
)


if prediction_df is None:

    st.error(
        f"No predictions found for "
        f"{MODEL_DISPLAY_NAMES[model_choice]}."
    )

    st.stop()


# ============================================================
# VALIDATE PREDICTION FILE
# ============================================================

required_prediction_columns = [
    "prediction",
    "actual",
]

missing_prediction_columns = [
    column
    for column in required_prediction_columns
    if column not in prediction_df.columns
]

if missing_prediction_columns:

    st.error(
        "The prediction file is missing required columns:"
    )

    st.write(
        missing_prediction_columns
    )

    st.stop()


# ============================================================
# VALIDATE ROW COUNT
# ============================================================

if len(prediction_df) != len(test_df):

    st.error(
        "Prediction file and test dataset "
        "do not contain the same number of rows."
    )

    st.write(
        f"Prediction rows: {len(prediction_df):,}"
    )

    st.write(
        f"Test rows: {len(test_df):,}"
    )

    st.stop()


# ============================================================
# CREATE ROW IDS
# ============================================================

test_df = test_df.copy()

test_df["_row_id"] = np.arange(
    len(test_df)
)


prediction_df = prediction_df.copy()

prediction_df["_row_id"] = np.arange(
    len(prediction_df)
)


# ============================================================
# ATTACH PRODUCT METADATA
# ============================================================
#
# IMPORTANT:
#
# Every model prediction must be aligned with stfore_test.csv.
#
# SARIMA's prediction file contains only:
#
#     prediction
#     actual
#
# Therefore product metadata is ALWAYS taken from
# stfore_test.csv.
#
# This prevents KeyError problems for:
#
#     external_code
#     retail
#     season
#     category
#
# ============================================================

for column in METADATA_COLUMNS:

    if column in prediction_df.columns:

        prediction_df = prediction_df.drop(
            columns=[
                column
            ]
        )


for column in METADATA_COLUMNS:

    prediction_df[column] = (
        test_df[
            column
        ].to_numpy()
    )


# ============================================================
# CONVERT NORMALIZED PREDICTIONS TO ACTUAL UNITS
# ============================================================

prediction_df[
    "forecast_units"
] = inverse_transform(
    prediction_df[
        "prediction"
    ].to_numpy()
)


prediction_df[
    "actual_units"
] = inverse_transform(
    prediction_df[
        "actual"
    ].to_numpy()
)


# ============================================================
# HISTORICAL SALES
# ============================================================

normalized_history = (
    test_df[
        HISTORY_COLUMNS
    ]
    .astype(float)
    .to_numpy()
)


historical_history_units = (
    inverse_transform(
        normalized_history
    )
)


# ============================================================
# ESTIMATED AVAILABLE STOCK
# ============================================================

estimated_stock = []

for row_index in range(
    len(test_df)
):

    normalized_restock = (
        test_df.iloc[
            row_index
        ][
            "restock"
        ]
    )

    history = (
        normalized_history[
            row_index
        ]
    )

    remaining_stock = (
        calculate_remaining_stock(
            normalized_restock,
            history,
        )
    )

    estimated_stock.append(
        remaining_stock
    )


prediction_df[
    "estimated_stock"
] = np.asarray(
    estimated_stock,
    dtype=float,
)


# ============================================================
# DEMAND VARIABILITY
# ============================================================

demand_std = np.std(
    historical_history_units,
    axis=1,
)


prediction_df[
    "demand_std_units"
] = demand_std


# ============================================================
# SAFETY STOCK
# ============================================================

prediction_df[
    "safety_stock_units"
] = calculate_safety_stock(
    demand_std=demand_std,
    lead_time=lead_time,
    service_level=service_level,
)


# ============================================================
# REORDER POINT
# ============================================================

prediction_df[
    "reorder_point_units"
] = calculate_reorder_point(
    forecast_demand=
        prediction_df[
            "forecast_units"
        ].to_numpy(),

    safety_stock=
        prediction_df[
            "safety_stock_units"
        ].to_numpy(),

    lead_time=lead_time,
)


# ============================================================
# RECOMMENDED ORDER QUANTITY
# ============================================================

stock_gap = (
    prediction_df[
        "reorder_point_units"
    ].to_numpy()

    -

    prediction_df[
        "estimated_stock"
    ].to_numpy()
)


prediction_df[
    "recommended_order"
] = np.ceil(
    np.maximum(
        stock_gap,
        0.0,
    )
).astype(int)


# ============================================================
# ORDER DECISION
# ============================================================

prediction_df[
    "status"
] = np.where(
    prediction_df[
        "recommended_order"
    ] > 0,
    "ORDER",
    "NO ORDER",
)


# ============================================================
# HISTORICAL RESTOCK SUMMARY
# ============================================================

restock_summary = (
    build_restock_summary(
        restocks_df
    )
)


prediction_df = prediction_df.merge(
    restock_summary,
    on=[
        "external_code",
        "retail",
    ],
    how="left",
)


for column in [
    "total_restock_units",
    "restock_events",
    "average_restock_units",
]:

    prediction_df[column] = (
        prediction_df[column]
        .fillna(0.0)
    )


# ============================================================
# SUMMARY METRICS
# ============================================================

total_products = len(
    prediction_df
)


total_forecast = (
    prediction_df[
        "forecast_units"
    ].sum()
)


products_requiring_order = (
    prediction_df[
        "recommended_order"
    ] > 0
).sum()


total_recommended_order = (
    prediction_df[
        "recommended_order"
    ].sum()
)


# ============================================================
# SUMMARY CARDS
# ============================================================

col1, col2, col3, col4 = (
    st.columns(4)
)


with col1:

    st.metric(
        "Product-Store Records",
        f"{total_products:,}",
    )


with col2:

    st.metric(
        "Forecast Demand",
        f"{total_forecast:,.0f} units",
    )


with col3:

    st.metric(
        "Products to Replenish",
        f"{products_requiring_order:,}",
    )


with col4:

    st.metric(
        "Recommended Order",
        f"{total_recommended_order:,} units",
    )


# ============================================================
# ORDER RECOMMENDATIONS
# ============================================================

st.header(
    "🛒 Order Recommendations"
)


st.caption(
    "Estimated stock is calculated from the normalized "
    "restock allocation minus legitimate historical sales. "
    "The normalization scalar is 53. Historical quantities "
    "from restocks.csv are already expressed as restock units."
)


# ============================================================
# PREPARE DISPLAY DATA
# ============================================================

display_df = (
    prediction_df.copy()
)


display_df["Product"] = (
    display_df[
        "external_code"
    ].astype(str)
)


display_df["Forecast"] = (
    display_df[
        "forecast_units"
    ].round(1)
)


display_df["Estimated Stock"] = (
    display_df[
        "estimated_stock"
    ].round(1)
)


display_df["Safety Stock"] = (
    display_df[
        "safety_stock_units"
    ].round(1)
)


display_df["Reorder Point"] = (
    display_df[
        "reorder_point_units"
    ].round(1)
)


display_df["Recommended Order"] = (
    display_df[
        "recommended_order"
    ].astype(int)
)


# ============================================================
# SORT TABLE
# ============================================================

display_df = display_df.sort_values(
    [
        "Recommended Order",
        "Reorder Point",
    ],
    ascending=[
        False,
        False,
    ],
)


# ============================================================
# MAIN INVENTORY TABLE
# ============================================================

table_columns = [
    "Product",
    "retail",
    "season",
    "category",
    "Forecast",
    "Estimated Stock",
    "Safety Stock",
    "Reorder Point",
    "Recommended Order",
    "status",
]


table_display = (
    display_df[
        table_columns
    ]
    .rename(
        columns={
            "retail":
                "Store",

            "season":
                "Season",

            "category":
                "Category",

            "status":
                "Decision",
        }
    )
)


st.dataframe(
    table_display,

    width="stretch",

    hide_index=True,

    column_config={

        "Product":
            st.column_config.TextColumn(
                "Product"
            ),

        "Store":
            st.column_config.NumberColumn(
                "Store"
            ),

        "Season":
            st.column_config.TextColumn(
                "Season"
            ),

        "Category":
            st.column_config.TextColumn(
                "Category"
            ),

        "Forecast":
            st.column_config.NumberColumn(
                "Forecast",
                format="%.1f"
            ),

        "Estimated Stock":
            st.column_config.NumberColumn(
                "Estimated Stock",
                format="%.1f"
            ),

        "Safety Stock":
            st.column_config.NumberColumn(
                "Safety Stock",
                format="%.1f"
            ),

        "Reorder Point":
            st.column_config.NumberColumn(
                "Reorder Point",
                format="%.1f"
            ),

        "Recommended Order":
            st.column_config.NumberColumn(
                "Order Qty",
                format="%d"
            ),

        "Decision":
            st.column_config.TextColumn(
                "Decision"
            ),
    },
)


st.caption(
    "Products are ranked by recommended replenishment "
    "quantity. All quantities are expressed in estimated "
    "physical units."
)


# ============================================================
# PRODUCT ANALYSIS
# ============================================================

st.header(
    "🔎 Product Analysis"
)


# ============================================================
# PRODUCT SELECTOR
# ============================================================

available_row_ids = (
    prediction_df[
        "_row_id"
    ].tolist()
)


selected_row_id = st.selectbox(
    "Select a product",

    available_row_ids,

    format_func=lambda row_id:
        (
            f"{test_df.loc[row_id, 'external_code']} "
            f"— {test_df.loc[row_id, 'category']} "
            f"— Store {test_df.loc[row_id, 'retail']}"
        ),
)


# ============================================================
# SELECTED PRODUCT
# ============================================================

selected_prediction_rows = (
    prediction_df[
        prediction_df[
            "_row_id"
        ]
        ==
        selected_row_id
    ]
)


if selected_prediction_rows.empty:

    st.error(
        "Unable to find the selected product."
    )

    st.stop()


selected = (
    selected_prediction_rows
    .iloc[0]
)


product_code = (
    selected[
        "external_code"
    ]
)


retail = (
    selected[
        "retail"
    ]
)


st.subheader(
    f"Product {product_code}"
)


# ============================================================
# PRODUCT METRICS
# ============================================================

detail1, detail2, detail3, detail4, detail5 = (
    st.columns(5)
)


with detail1:

    st.metric(
        "Forecast",
        f"{selected['forecast_units']:.1f} units"
    )


with detail2:

    st.metric(
        "Estimated Stock",
        f"{selected['estimated_stock']:.1f} units"
    )


with detail3:

    st.metric(
        "Safety Stock",
        f"{selected['safety_stock_units']:.1f} units"
    )


with detail4:

    st.metric(
        "Reorder Point",
        f"{selected['reorder_point_units']:.1f} units"
    )


with detail5:

    st.metric(
        "Order Quantity",
        f"{int(selected['recommended_order'])} units"
    )


# ============================================================
# ORDER DECISION
# ============================================================

if selected[
    "recommended_order"
] > 0:

    st.warning(
        f"🛒 ORDER "
        f"{int(selected['recommended_order'])} UNITS"
    )

else:

    st.success(
        "✓ NO ORDER REQUIRED"
    )


# ============================================================
# PRODUCT INFORMATION
# ============================================================

info_col1, info_col2 = (
    st.columns(2)
)


with info_col1:

    st.write(
        f"**Category:** "
        f"{selected['category']}"
    )

    st.write(
        f"**Season:** "
        f"{selected['season']}"
    )

    st.write(
        f"**Store:** "
        f"{selected['retail']}"
    )

    st.write(
        f"**Forecasting Model:** "
        f"{MODEL_DISPLAY_NAMES[model_choice]}"
    )


with info_col2:

    st.write(
        f"**Demand Variability:** "
        f"{selected['demand_std_units']:.1f} units"
    )

    st.write(
        f"**Safety Stock:** "
        f"{selected['safety_stock_units']:.1f} units"
    )

    st.write(
        f"**Historical Restock:** "
        f"{selected['total_restock_units']:.0f} units"
    )

    st.write(
        f"**Restock Events:** "
        f"{int(selected['restock_events'])}"
    )


# ============================================================
# HISTORICAL DEMAND
# ============================================================

st.subheader(
    "📈 Historical Demand"
)


selected_history = (
    historical_history_units[
        selected_row_id
    ]
)


history_chart = pd.DataFrame(
    {
        "Period":
            list(range(1, 12)),

        "Demand Units":
            selected_history,
    }
)


st.line_chart(
    history_chart.set_index(
        "Period"
    )
)


# ============================================================
# FORECAST VS ACTUAL
# ============================================================

st.subheader(
    "Forecast vs Actual"
)


forecast_value = float(
    selected[
        "forecast_units"
    ]
)


actual_value = float(
    selected[
        "actual_units"
    ]
)


forecast_actual_df = pd.DataFrame(
    {
        "Value": [
            forecast_value,
            actual_value,
        ]
    },

    index=[
        "Forecast",
        "Actual",
    ],
)


st.bar_chart(
    forecast_actual_df
)


# ============================================================
# HISTORICAL RESTOCKING
# ============================================================

st.subheader(
    "📦 Historical Restocking"
)


product_restocks = (
    get_product_restock_history(
        restocks_df,
        product_code,
        retail,
    )
)


if product_restocks.empty:

    st.info(
        "No historical restock records were "
        "found for this product/store combination."
    )

else:

    restock_display = (
        product_restocks[
            [
                "week",
                "year",
                "restock_units",
            ]
        ]
        .rename(
            columns={
                "week":
                    "Week",

                "year":
                    "Year",

                "restock_units":
                    "Restock Quantity (Units)",
            }
        )
    )

    st.dataframe(
        restock_display,
        width="stretch",
        hide_index=True,
    )


# ============================================================
# MODEL COMPARISON
# ============================================================

st.header(
    "📊 Model Comparison"
)


comparison_df = (
    load_model_comparison()
)


if comparison_df is not None:

    comparison_display = (
        comparison_df.copy()
    )


    # --------------------------------------------------------
    # Format metrics
    # --------------------------------------------------------

    if "MAE" in comparison_display.columns:

        comparison_display[
            "MAE"
        ] = (
            comparison_display[
                "MAE"
            ]
            .round(6)
        )


    if "RMSE" in comparison_display.columns:

        comparison_display[
            "RMSE"
        ] = (
            comparison_display[
                "RMSE"
            ]
            .round(6)
        )


    if "MAPE" in comparison_display.columns:

        comparison_display[
            "MAPE"
        ] = (
            comparison_display[
                "MAPE"
            ]
            .round(2)
        )


    if (
        "Training_Time_Seconds"
        in comparison_display.columns
    ):

        comparison_display[
            "Training_Time_Seconds"
        ] = (
            comparison_display[
                "Training_Time_Seconds"
            ]
            .round(2)
        )


    st.dataframe(
        comparison_display,
        width="stretch",
        hide_index=True,
    )


else:

    st.info(
        "Run model comparison to display "
        "forecasting performance."
    )


# ============================================================
# INVENTORY METHODOLOGY
# ============================================================

st.divider()


with st.expander(
    "ℹ️ How the inventory recommendation works"
):

    st.markdown(
        """
        ### 1. Demand Forecast

        The selected forecasting model predicts demand
        for the next period.

        ### 2. Convert Forecast to Actual Units

        Visuelle 2.0 sales values are normalized.

        The normalization scalar is **53**.

        **Actual Units = Normalized Value × 53**

        ### 3. Estimate Available Stock

        The `restock` field in `stfore_test.csv`
        is normalized.

        **Stock Allocation = Normalized Restock × 53**

        Historical legitimate sales are deducted
        from this allocation.

        ### 4. Safety Stock

        **Safety Stock = Z × Demand Std × √Lead Time**

        The Z value depends on the selected service level.

        ### 5. Reorder Point

        **Reorder Point = Forecast Demand × Lead Time + Safety Stock**

        ### 6. Recommended Order

        **Recommended Order = max(Reorder Point − Estimated Stock, 0)**

        The result is rounded up to a whole unit.

        ### Important

        The recommended quantity is an inventory-planning
        estimate based on the information available in
        Visuelle 2.0.

        It is **not a live warehouse inventory measurement**.
        """
    )


# ============================================================
# FOOTER
# ============================================================

st.caption(
    "AI-Driven Fashion Demand Forecasting and Inventory "
    "Optimization | Visuelle 2.0"
)